# Python SSL certificate conversion tool.
# Download and converts SSL certs from PEM format into a C header that can be
# referenced from a sketch to load the certificate data (in binary DER format).
# Modified by the OPEnS lab to output certificate data in a format supported by
# BearSSL. 
# Author: Tony DiCola, Modified by Noah Koontz
#
# Dependencies:
#   click - Install with 'sudo pip install click' (omit sudo on windows)
#   PyOpenSSL - See homepage: https://pyopenssl.readthedocs.org/en/latest/
#               Should just be a 'sudo pip install pyopenssl' command, HOWEVER
#               on Windows you probably need a precompiled binary version.  Try
#               installing with pip and if you see errors when running that
#               OpenSSL can't be found then try installing egenix's prebuilt
#               PyOpenSSL library and OpenSSL lib:
#                 http://www.egenix.com/products/python/pyOpenSSL/
#   certifi - Install with 'sudo pip install certifi' (omit sudo on windows)
import click
import certifi
from pathlib import Path
import re
import tempfile

IMPORT_ERROR = None

try:
  import cert_util
except ModuleNotFoundError as exc:
  cert_util = None
  IMPORT_ERROR = exc

try:
  from OpenSSL import crypto
except ModuleNotFoundError as exc:
  crypto = None
  if IMPORT_ERROR is None:
    IMPORT_ERROR = exc

# Default name for the cert length varible
CERT_LENGTH_NAME = "TAs_NUM"
# Defualt name for the cert array varible
CERT_ARRAY_NAME = "TAs"
TELEGRAM_DOMAIN = "api.telegram.org"
TOOL_DIR = Path(__file__).resolve().parent
LIBRARY_ROOT = TOOL_DIR.parent.parent
DEFAULT_TELEGRAM_CRT = TOOL_DIR / "ca.crt"
DEFAULT_TELEGRAM_HEADER = LIBRARY_ROOT / "src" / "tg_certificate.h"
DEFAULT_TELEGRAM_BEARSSL_HEADER = LIBRARY_ROOT / "src" / "tg_bearssl_certificate.h"


def ensure_runtime_dependencies():
  if IMPORT_ERROR is None:
    return

  raise click.ClickException(
      "Missing Python dependency: {0}. Install the tool requirements with "
      '"python -m pip install -r tools/pycert_bearssl/requirements.txt".'.format(IMPORT_ERROR.name)
  )


def confirm_overwrite(paths, skip_confirmation=False):
  existing_paths = [Path(path) for path in paths if Path(path).exists()]
  if skip_confirmation or not existing_paths:
    return

  click.echo("The following files already exist and will be overwritten:")
  for path in existing_paths:
    click.echo(f"  - {path}")

  if not click.confirm("Do you want to continue?", default=False):
    raise click.Abort()


def write_pem_certificate(cert, output_path):
  ensure_runtime_dependencies()
  output_path.parent.mkdir(parents=True, exist_ok=True)
  with output_path.open("wb") as output_file:
    output_file.write(crypto.dump_certificate(crypto.FILETYPE_PEM, cert))


def write_header(certs, cert_var, cert_length_var, output_path, keep_dupes=False, domains=None):
  ensure_runtime_dependencies()
  output_path.parent.mkdir(parents=True, exist_ok=True)
  with output_path.open("w", newline="\n") as output_file:
    cert_util.x509_to_header(certs, cert_var, cert_length_var, output_file, keep_dupes, domains=domains)


def make_header_guard(output_path):
  stem = Path(output_path).stem.upper()
  normalized = re.sub(r'[^A-Z0-9]+', '_', stem).strip('_')
  return '_{0}_H_'.format(normalized)


def write_text_file(text, output_path):
  output_path.parent.mkdir(parents=True, exist_ok=True)
  output_path.write_text(text, encoding="utf-8", newline="\n")


def write_pem_header(cert, output_path):
  ensure_runtime_dependencies()
  pem_text = crypto.dump_certificate(crypto.FILETYPE_PEM, cert).decode("ascii").strip()
  guard = make_header_guard(output_path)
  header_text = (
      '#ifndef {guard}\n'
      '#define {guard}\n\n'
      '#ifdef __cplusplus\n'
      'extern "C"\n'
      '{{\n'
      '#endif\n\n'
      '/* This file is auto-generated by the pycert_bearssl tool.  Do not change it manually. */\n\n'
      'static const char telegram_cert[] PROGMEM = R"EOF(\n{pem}\n)EOF";\n\n'
      '#ifdef __cplusplus\n'
      '}} /* extern "C" */\n'
      '#endif\n\n'
      '#endif /* ifndef {guard} */\n'
  ).format(guard=guard, pem=pem_text)
  write_text_file(header_text, output_path)


def write_bearssl_header(certs, cert_var, cert_length_var, output_path, keep_dupes=False, domains=None):
  ensure_runtime_dependencies()
  with tempfile.NamedTemporaryFile("w", delete=False, newline="\n", suffix=".h") as temp_file:
    temp_path = Path(temp_file.name)

  try:
    write_header(certs, cert_var, cert_length_var, temp_path, keep_dupes=keep_dupes, domains=domains)
    header_text = temp_path.read_text(encoding="utf-8")
  finally:
    if temp_path.exists():
      temp_path.unlink()

  guard = make_header_guard(output_path)
  header_text = re.sub(r'^#ifndef\s+.*$', '#ifndef {0}'.format(guard), header_text, count=1, flags=re.MULTILINE)
  header_text = re.sub(r'^#define\s+.*$', '#define {0}'.format(guard), header_text, count=1, flags=re.MULTILINE)
  header_text = re.sub(r'^#endif /\* ifndef .* \*/$', '#endif /* ifndef {0} */'.format(guard), header_text, count=1, flags=re.MULTILINE)
  write_text_file(header_text, output_path)

# Click setup and commands:
@click.group()
def pycert_bearssl():
    """OPEnS Python Certificate Tool
    This is a tool to download and convert SSL certificates and certificate
    chains into a C header format that can be imported into BearSSL
    """
    pass

@pycert_bearssl.command(short_help='Download SSL certs and save as a C header.')
@click.option('--port', '-p', type=click.INT, default=443,
              help='port to use for reading certificate (default 443, SSL)')
@click.option('--cert-var', '-c', default=CERT_ARRAY_NAME,
              help='name of the variable in the header which will contain certificate data (default: {0})'.format(CERT_ARRAY_NAME))
@click.option('--cert-length-var', '-l', default=CERT_LENGTH_NAME,
              help='name of the define in the header which will contain the length of the certificate data (default: {0})'.format(CERT_LENGTH_NAME))
@click.option('--output', '-o', type=click.File('w'), default='certificates.h',
              help='name of the output file (default: certificates.h)')
@click.option('--use-store', '-s', type=click.File('r'), default=certifi.where(),
              help='the location of the .pem file containing a list of trusted root certificates (default: use certifi.where())')
@click.option('--keep-dupes', '-d', is_flag=True, default=False,
              help='write all certs including any duplicates across domains (default: remove duplicates)')
@click.argument('domain', nargs=-1)
def download(port, cert_var, cert_length_var, output, use_store, keep_dupes, domain):
    """Download the SSL certificates for specified domain(s) and save them as a C
    header file that can be imported into a sketch.
    Provide at least one argument that is the domain to query for its SSL
    certificate, for example google.com for Google's SSL certificate.  You can
    provide any number of domains as additional arguments.  All of the certificates
    will be combined into a single output header.
    By default the file 'certificates.h' will be created, however you can change
    the name of the file with the --output option.
    If a chain of certificates is retrieved then only the root certificate (i.e.
    the last in the chain) will be saved.  However you can override this and
    force the full chain to be saved with the --full-chain option.
    Example of downloading google.com's SSL certificate and storing it in
    certificates.h:
      pycert download google.com
    Example of downloading google.com and adafruit.com's SSL certificates and
    storing them in data.h:
      pycert download --output data.h google.com adafruit.com
    Note that the certificates will be validated before they are downloaded!
    """
    ensure_runtime_dependencies()
    # if array is emptey, exit
    if len(domain) == 0:
      return
    # prepare the root certificate store
    cert_obj_store = cert_util.parse_root_certificate_store(use_store)
    cert_dict = dict([(cert.get_subject().hash(), cert) for cert in cert_obj_store])
    # Download the cert object for each provided domain.
    down_certs = []
    for d in domain:
        # Download the certificate (unfortunately python will _always_ try to
        # validate it so we have no control over turning that off).
        cert = cert_util.get_server_root_cert(d, port, cert_dict)
        if cert is None:
            raise click.ClickException('Could not download and/or validate the certificate for {0} port {1}!'.format(d, port))
        click.echo('Retrieved certificate for {0}'.format(d))
        # append cert to array
        down_certs.append(cert)
    # Combine PEMs and write output header.
    try:
      cert_util.x509_to_header(down_certs, cert_var, cert_length_var, output, keep_dupes, domains=domain)
    except Exception as E:
      click.echo(f'Recieved error when converting certificate to header: {E}')
      exit(1)


@pycert_bearssl.command(short_help='Convert PEM certs into a C header.')
@click.option('--cert-var', '-c', default=CERT_ARRAY_NAME,
              help='name of the variable in the header which will contain certificate data (default: {0})'.format(CERT_ARRAY_NAME))
@click.option('--cert-length-var', '-l', default=CERT_LENGTH_NAME,
              help='name of the define in the header which will contain the length of the certificate data (default: {0})'.format(CERT_LENGTH_NAME))
@click.option('--output', '-o', type=click.File('w'), default='certificates.h',
              help='name of the output file (default: certificates.h)')
@click.option('--use-store', '-s', type=click.File('r'), default=certifi.where(),
              help='the location of the .pem file containing a list of trusted root certificates (default: use certifi.where())')
@click.option('--keep-dupes', '-d', is_flag=True, default=False,
              help='write all certs including any duplicates (default: remove duplicates)')
@click.option('--no-search', '-n', is_flag=True, default=False,
              help='Do not attempt to search for a root certificate to the provided PEM files, instead treat the PEM files as the root certificates')
@click.argument('cert', type=click.File('r'), nargs=-1)
def convert(cert_var, cert_length_var, output, use_store, keep_dupes, no_search, cert):
    """Convert PEM certificates into a C header that can be imported into a
    sketch.  Specify each certificate to encode as a separate argument (each
    must be in PEM format) and they will be merged into a single file.
    By default the file 'certificates.h' will be created, however you can change
    the name of the file with the --output option.
    If a chain of certificates is found then only the root certificate (i.e.
    the last in the chain) will be saved.
    Example of converting a foo.pem certificate into a certificates.h header:
      pycert convert foo.pem
    Example of converting foo.pem and bar.pem certificates into data.h:
      pycert convert foo.pem bar.pem
    """
    ensure_runtime_dependencies()
    # if array is emptey, exit
    if len(cert) == 0:
      return
    # prepare root certificate store
    cert_obj_store = cert_util.parse_root_certificate_store(use_store)
    cert_dict = dict([(cert.get_subject().hash(), cert) for cert in cert_obj_store])
    # Load all the provided PEM files.
    cert_objs = []
    for c in cert:
        cert_pem = c.read()
        cert_parsed = crypto.load_certificate(crypto.FILETYPE_PEM, cert_pem)
        if cert_parsed is None:
          click.echo('Failed to load certificate {0}'.format(c.name))
        else:
          click.echo('Loaded certificate {0}'.format(c.name))
          cert_objs.append(cert_parsed)
    # find a root certificate for each
    root_certs = []
    if no_search:
      root_certs = cert_objs
    else:
      for i, c in enumerate(cert_objs):
        cn_hash = c.get_issuer().hash()
        if cn_hash not in cert_dict:
          click.echo('Could not find a root certificate for {0}'.format(cert[i].name))
        else:
          root_certs.append(cert_dict[cn_hash])
    # Combine PEMs and write output header.
    try:
      cert_util.x509_to_header(root_certs, cert_var, cert_length_var, output, keep_dupes)
    except Exception as E:
      click.echo(f'Recieved error when converting certificate to header: {E}')
      exit(1)
@pycert_bearssl.command(name='update-telegram', short_help='Download Telegram CA data and generate tg_certificate.h.')
@click.option('--domain', default=TELEGRAM_DOMAIN, show_default=True,
        help='Telegram API hostname to inspect.')
@click.option('--port', '-p', type=click.INT, default=443,
        help='port to use for reading certificate (default 443, SSL)')
@click.option('--cert-var', '-c', default=CERT_ARRAY_NAME,
        help='name of the variable in the header which will contain certificate data (default: {0})'.format(CERT_ARRAY_NAME))
@click.option('--cert-length-var', '-l', default=CERT_LENGTH_NAME,
        help='name of the define in the header which will contain the length of the certificate data (default: {0})'.format(CERT_LENGTH_NAME))
@click.option('--crt-output', default=str(DEFAULT_TELEGRAM_CRT), show_default=True,
        help='path of the PEM/CRT file generated from the Telegram trust anchor')
@click.option('--header-output', default=str(DEFAULT_TELEGRAM_HEADER), show_default=True,
  help='path of the generated native Telegram PEM header for AsyncTelegram2')
@click.option('--bearssl-header-output', default=str(DEFAULT_TELEGRAM_BEARSSL_HEADER), show_default=True,
  help='path of the generated BearSSL trust-anchor header for SSLClient examples')
@click.option('--use-store', '-s', type=click.File('r'), default=certifi.where(),
        help='the location of the .pem file containing a list of trusted root certificates (default: use certifi.where())')
@click.option('--yes', '-y', is_flag=True, default=False,
        help='overwrite existing output files without confirmation')
def update_telegram(domain, port, cert_var, cert_length_var, crt_output, header_output, bearssl_header_output, use_store, yes):
    """Resolve Telegram's trust anchor, save it as a .crt file and generate Telegram headers."""
    ensure_runtime_dependencies()
    cert_obj_store = cert_util.parse_root_certificate_store(use_store)
    cert_dict = dict([(cert.get_subject().hash(), cert) for cert in cert_obj_store])
    cert = cert_util.get_server_root_cert(domain, port, cert_dict)
    if cert is None:
      raise click.ClickException('Could not download and/or validate the certificate for {0} port {1}!'.format(domain, port))

    crt_output_path = Path(crt_output).resolve()
    header_output_path = Path(header_output).resolve()
    bearssl_header_output_path = Path(bearssl_header_output).resolve()
    confirm_overwrite([crt_output_path, header_output_path, bearssl_header_output_path], skip_confirmation=yes)

    write_pem_certificate(cert, crt_output_path)
    write_pem_header(cert, header_output_path)
    write_bearssl_header([cert], cert_var, cert_length_var, bearssl_header_output_path, domains=[domain])

    click.echo(f'Saved Telegram trust anchor to {crt_output_path}')
    click.echo(f'Generated native Telegram certificate header at {header_output_path}')
    click.echo(f'Generated BearSSL trust-anchor header at {bearssl_header_output_path}')

if __name__ == '__main__':
    pycert_bearssl()