.TH "src/AsyncTelegram2.h" 3 "Sun Feb 26 2023" "AsyncTelegram2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/AsyncTelegram2.h
.SH SYNOPSIS
.br
.PP
\fC#include <ArduinoJson\&.h>\fP
.br
\fC#include 'Client\&.h'\fP
.br
\fC#include 'time\&.h'\fP
.br
\fC#include 'DataStructures\&.h'\fP
.br
\fC#include 'InlineKeyboard\&.h'\fP
.br
\fC#include 'ReplyKeyboard\&.h'\fP
.br
\fC#include 'serial_log\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAsyncTelegram2\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBARDUINOJSON_USE_LONG_LONG\fP   1"
.br
.ti -1c
.RI "#define \fBARDUINOJSON_DECODE_UNICODE\fP   1"
.br
.ti -1c
.RI "#define \fBFS_SUPPORT\fP   false"
.br
.ti -1c
.RI "#define \fBLED_BUILTIN\fP   2"
.br
.ti -1c
.RI "#define \fBDEBUG_ENABLE\fP   0"
.br
.ti -1c
.RI "#define \fBFS_SUPPORT\fP   false"
.br
.ti -1c
.RI "#define \fBINT32\fP   'ld'"
.br
.ti -1c
.RI "#define \fBMAX_INLINEKYB_CB\fP   30"
.br
.ti -1c
.RI "#define \fBSERVER_TIMEOUT\fP   10000"
.br
.ti -1c
.RI "#define \fBMIN_UPDATE_TIME\fP   500"
.br
.ti -1c
.RI "#define \fBBLOCK_SIZE\fP   1436"
.br
.ti -1c
.RI "#define \fBTELEGRAM_HOST\fP   'api\&.telegram\&.org'"
.br
.ti -1c
.RI "#define \fBTELEGRAM_IP\fP   '149\&.154\&.167\&.220'"
.br
.ti -1c
.RI "#define \fBTELEGRAM_PORT\fP   443"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ARDUINOJSON_DECODE_UNICODE   1"

.PP
Definition at line \fB6\fP of file \fBAsyncTelegram2\&.h\fP\&.
.SS "#define ARDUINOJSON_USE_LONG_LONG   1"

.PP
Definition at line \fB5\fP of file \fBAsyncTelegram2\&.h\fP\&.
.SS "#define BLOCK_SIZE   1436"

.PP
Definition at line \fB54\fP of file \fBAsyncTelegram2\&.h\fP\&.
.SS "#define DEBUG_ENABLE   0"

.PP
Definition at line \fB25\fP of file \fBAsyncTelegram2\&.h\fP\&.
.SS "#define FS_SUPPORT   false"

.PP
Definition at line \fB33\fP of file \fBAsyncTelegram2\&.h\fP\&.
.SS "#define FS_SUPPORT   false"

.PP
Definition at line \fB33\fP of file \fBAsyncTelegram2\&.h\fP\&.
.SS "#define INT32   'ld'"

.PP
Definition at line \fB41\fP of file \fBAsyncTelegram2\&.h\fP\&.
.SS "#define LED_BUILTIN   2"

.PP
Definition at line \fB18\fP of file \fBAsyncTelegram2\&.h\fP\&.
.SS "#define MAX_INLINEKYB_CB   30"

.PP
Definition at line \fB49\fP of file \fBAsyncTelegram2\&.h\fP\&.
.SS "#define MIN_UPDATE_TIME   500"

.PP
Definition at line \fB52\fP of file \fBAsyncTelegram2\&.h\fP\&.
.SS "#define SERVER_TIMEOUT   10000"

.PP
Definition at line \fB51\fP of file \fBAsyncTelegram2\&.h\fP\&.
.SS "#define TELEGRAM_HOST   'api\&.telegram\&.org'"

.PP
Definition at line \fB61\fP of file \fBAsyncTelegram2\&.h\fP\&.
.SS "#define TELEGRAM_IP   '149\&.154\&.167\&.220'"

.PP
Definition at line \fB62\fP of file \fBAsyncTelegram2\&.h\fP\&.
.SS "#define TELEGRAM_PORT   443"

.PP
Definition at line \fB63\fP of file \fBAsyncTelegram2\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AsyncTelegram2 from the source code\&.
