.TH "src/AsyncTelegram2.cpp" 3 "Sun Feb 26 2023" "AsyncTelegram2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/AsyncTelegram2.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'AsyncTelegram2\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHEADERS_END\fP   '\\r\\n\\r\\n'"
.br
.ti -1c
.RI "#define \fBBOUNDARY\fP   '\-\-\-\-WebKitFormBoundary7MA4YWxkTrZu0gW'"
.br
.ti -1c
.RI "#define \fBEND_BOUNDARY\fP   '\\r\\n\-\-' BOUNDARY '\-\-\\r\\n'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BOUNDARY   '\-\-\-\-WebKitFormBoundary7MA4YWxkTrZu0gW'"

.SS "#define END_BOUNDARY   '\\r\\n\-\-' BOUNDARY '\-\-\\r\\n'"

.SS "#define HEADERS_END   '\\r\\n\\r\\n'"

.PP
Definition at line \fB3\fP of file \fBAsyncTelegram2\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AsyncTelegram2 from the source code\&.
