.TH "src/ReplyKeyboard.h" 3 "Sun Feb 26 2023" "AsyncTelegram2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ReplyKeyboard.h
.SH SYNOPSIS
.br
.PP
\fC#include <ArduinoJson\&.h>\fP
.br
\fC#include 'DataStructures\&.h'\fP
.br
\fC#include 'serial_log\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReplyKeyboard\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBARDUINOJSON_USE_LONG_LONG\fP   1"
.br
.ti -1c
.RI "#define \fBARDUINOJSON_DECODE_UNICODE\fP   1"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBReplyKeyboardButtonType\fP { \fBKeyboardButtonSimple\fP = 1, \fBKeyboardButtonContact\fP = 2, \fBKeyboardButtonLocation\fP = 3 }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ARDUINOJSON_DECODE_UNICODE   1"

.PP
Definition at line \fB6\fP of file \fBReplyKeyboard\&.h\fP\&.
.SS "#define ARDUINOJSON_USE_LONG_LONG   1"

.PP
Definition at line \fB5\fP of file \fBReplyKeyboard\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBReplyKeyboardButtonType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIKeyboardButtonSimple \fP\fP
.TP
\fB\fIKeyboardButtonContact \fP\fP
.TP
\fB\fIKeyboardButtonLocation \fP\fP
.PP
Definition at line \fB11\fP of file \fBReplyKeyboard\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AsyncTelegram2 from the source code\&.
