.TH "src/serial_log.h" 3 "Sun Feb 26 2023" "AsyncTelegram2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/serial_log.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBlog_debug\fP(format, \&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBlog_warning\fP(args)"
.br
.ti -1c
.RI "#define \fBlog_info\fP(x)"
.br
.ti -1c
.RI "#define \fBlog_error\fP(x)"
.br
.ti -1c
.RI "#define \fBdebugJson\fP(X,  Y)"
.br
.ti -1c
.RI "#define \fBerrorJson\fP(E)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define debugJson(X, Y)"

.PP
Definition at line \fB49\fP of file \fBserial_log\&.h\fP\&.
.SS "#define errorJson(E)"

.PP
Definition at line \fB50\fP of file \fBserial_log\&.h\fP\&.
.SS "#define log_debug(format,  \&.\&.\&.)"

.PP
Definition at line \fB44\fP of file \fBserial_log\&.h\fP\&.
.SS "#define log_error(x)"

.PP
Definition at line \fB47\fP of file \fBserial_log\&.h\fP\&.
.SS "#define log_info(x)"

.PP
Definition at line \fB46\fP of file \fBserial_log\&.h\fP\&.
.SS "#define log_warning(args)"

.PP
Definition at line \fB45\fP of file \fBserial_log\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AsyncTelegram2 from the source code\&.
