.TH "TBContact" 3 "Sun Feb 26 2023" "AsyncTelegram2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TBContact
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataStructures\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBid\fP"
.br
.ti -1c
.RI "String \fBphoneNumber\fP"
.br
.ti -1c
.RI "String \fBfirstName\fP"
.br
.ti -1c
.RI "String \fBlastName\fP"
.br
.ti -1c
.RI "String \fBvCard\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB35\fP of file \fBDataStructures\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "String TBContact::firstName"

.PP
Definition at line \fB38\fP of file \fBDataStructures\&.h\fP\&.
.SS "int64_t TBContact::id"

.PP
Definition at line \fB36\fP of file \fBDataStructures\&.h\fP\&.
.SS "String TBContact::lastName"

.PP
Definition at line \fB39\fP of file \fBDataStructures\&.h\fP\&.
.SS "String TBContact::phoneNumber"

.PP
Definition at line \fB37\fP of file \fBDataStructures\&.h\fP\&.
.SS "String TBContact::vCard"

.PP
Definition at line \fB40\fP of file \fBDataStructures\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AsyncTelegram2 from the source code\&.
