.TH "TBDocument" 3 "Sun Feb 26 2023" "AsyncTelegram2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TBDocument
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataStructures\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBfile_exists\fP"
.br
.ti -1c
.RI "int32_t \fBfile_size\fP"
.br
.ti -1c
.RI "String \fBfile_id\fP"
.br
.ti -1c
.RI "String \fBfile_name\fP"
.br
.ti -1c
.RI "String \fBfile_path\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB43\fP of file \fBDataStructures\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool TBDocument::file_exists"

.PP
Definition at line \fB44\fP of file \fBDataStructures\&.h\fP\&.
.SS "String TBDocument::file_id"

.PP
Definition at line \fB46\fP of file \fBDataStructures\&.h\fP\&.
.SS "String TBDocument::file_name"

.PP
Definition at line \fB47\fP of file \fBDataStructures\&.h\fP\&.
.SS "String TBDocument::file_path"

.PP
Definition at line \fB48\fP of file \fBDataStructures\&.h\fP\&.
.SS "int32_t TBDocument::file_size"

.PP
Definition at line \fB45\fP of file \fBDataStructures\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AsyncTelegram2 from the source code\&.
