.TH "TBLocation" 3 "Sun Feb 26 2023" "AsyncTelegram2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TBLocation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataStructures\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBlongitude\fP"
.br
.ti -1c
.RI "float \fBlatitude\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBDataStructures\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float TBLocation::latitude"

.PP
Definition at line \fB32\fP of file \fBDataStructures\&.h\fP\&.
.SS "float TBLocation::longitude"

.PP
Definition at line \fB31\fP of file \fBDataStructures\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AsyncTelegram2 from the source code\&.
