.TH "TBMessage" 3 "Sun Feb 26 2023" "AsyncTelegram2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TBMessage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataStructures\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMessageType\fP \fBmessageType\fP"
.br
.ti -1c
.RI "bool \fBisHTMLenabled\fP = true"
.br
.ti -1c
.RI "bool \fBisMarkdownEnabled\fP = false"
.br
.ti -1c
.RI "bool \fBdisable_notification\fP = false"
.br
.ti -1c
.RI "bool \fBforce_reply\fP = false"
.br
.ti -1c
.RI "int32_t \fBdate\fP"
.br
.ti -1c
.RI "int32_t \fBchatInstance\fP"
.br
.ti -1c
.RI "int64_t \fBchatId\fP"
.br
.ti -1c
.RI "int32_t \fBmessageID\fP"
.br
.ti -1c
.RI "\fBTBUser\fP \fBsender\fP"
.br
.ti -1c
.RI "\fBTBUser\fP \fBmember\fP"
.br
.ti -1c
.RI "\fBTBLocation\fP \fBlocation\fP"
.br
.ti -1c
.RI "\fBTBContact\fP \fBcontact\fP"
.br
.ti -1c
.RI "\fBTBDocument\fP \fBdocument\fP"
.br
.ti -1c
.RI "int64_t \fBcallbackQueryID\fP"
.br
.ti -1c
.RI "String \fBcallbackQueryData\fP"
.br
.ti -1c
.RI "String \fBtext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB51\fP of file \fBDataStructures\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "String TBMessage::callbackQueryData"

.PP
Definition at line \fB67\fP of file \fBDataStructures\&.h\fP\&.
.SS "int64_t TBMessage::callbackQueryID"

.PP
Definition at line \fB66\fP of file \fBDataStructures\&.h\fP\&.
.SS "int64_t TBMessage::chatId"

.PP
Definition at line \fB59\fP of file \fBDataStructures\&.h\fP\&.
.SS "int32_t TBMessage::chatInstance"

.PP
Definition at line \fB58\fP of file \fBDataStructures\&.h\fP\&.
.SS "\fBTBContact\fP TBMessage::contact"

.PP
Definition at line \fB64\fP of file \fBDataStructures\&.h\fP\&.
.SS "int32_t TBMessage::date"

.PP
Definition at line \fB57\fP of file \fBDataStructures\&.h\fP\&.
.SS "bool TBMessage::disable_notification = false"

.PP
Definition at line \fB55\fP of file \fBDataStructures\&.h\fP\&.
.SS "\fBTBDocument\fP TBMessage::document"

.PP
Definition at line \fB65\fP of file \fBDataStructures\&.h\fP\&.
.SS "bool TBMessage::force_reply = false"

.PP
Definition at line \fB56\fP of file \fBDataStructures\&.h\fP\&.
.SS "bool TBMessage::isHTMLenabled = true"

.PP
Definition at line \fB53\fP of file \fBDataStructures\&.h\fP\&.
.SS "bool TBMessage::isMarkdownEnabled = false"

.PP
Definition at line \fB54\fP of file \fBDataStructures\&.h\fP\&.
.SS "\fBTBLocation\fP TBMessage::location"

.PP
Definition at line \fB63\fP of file \fBDataStructures\&.h\fP\&.
.SS "\fBTBUser\fP TBMessage::member"

.PP
Definition at line \fB62\fP of file \fBDataStructures\&.h\fP\&.
.SS "int32_t TBMessage::messageID"

.PP
Definition at line \fB60\fP of file \fBDataStructures\&.h\fP\&.
.SS "\fBMessageType\fP TBMessage::messageType"

.PP
Definition at line \fB52\fP of file \fBDataStructures\&.h\fP\&.
.SS "\fBTBUser\fP TBMessage::sender"

.PP
Definition at line \fB61\fP of file \fBDataStructures\&.h\fP\&.
.SS "String TBMessage::text"

.PP
Definition at line \fB68\fP of file \fBDataStructures\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AsyncTelegram2 from the source code\&.
