.TH "TBUser" 3 "Sun Feb 26 2023" "AsyncTelegram2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TBUser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataStructures\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisBot\fP"
.br
.ti -1c
.RI "int64_t \fBid\fP = 0"
.br
.ti -1c
.RI "String \fBfirstName\fP"
.br
.ti -1c
.RI "String \fBlastName\fP"
.br
.ti -1c
.RI "String \fBusername\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB22\fP of file \fBDataStructures\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "String TBUser::firstName"

.PP
Definition at line \fB25\fP of file \fBDataStructures\&.h\fP\&.
.SS "int64_t TBUser::id = 0"

.PP
Definition at line \fB24\fP of file \fBDataStructures\&.h\fP\&.
.SS "bool TBUser::isBot"

.PP
Definition at line \fB23\fP of file \fBDataStructures\&.h\fP\&.
.SS "String TBUser::lastName"

.PP
Definition at line \fB26\fP of file \fBDataStructures\&.h\fP\&.
.SS "String TBUser::username"

.PP
Definition at line \fB27\fP of file \fBDataStructures\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AsyncTelegram2 from the source code\&.
