name: Clean Workflow Logs
on:
  workflow_dispatch:
    inputs:
      keep_minimum_runs:
        description: "Numero di workflow recenti da mantenere"
        default: "5"
        required: false
jobs:
  clean-logs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0  # Imposta a 0 per ignorare la data e considerare solo keep_minimum_runs
          keep_minimum_runs: ${{ github.event.inputs.keep_minimum_runs }}
